version: "3"

services:
  baidu:
    image: local/baidupcs
    container_name: baidupcs
    network_mode: local_work
    restart: unless-stopped
    ports:
      - 5299:5299
    volumes:
      - "./data-download:/root/Downloads"
      - ./config:/root/.config/BaiduPCS-Go