version: "3"

services:
  filebrowser:
    image: cwxyz/filebrowser
    container_name: fbrowser
    network_mode: local_work
    ports:
      - 6655:3000
    expose: 
      - 3000
    volumes:
      - /media/pi/gem:/app/data
    restart: unless-stopped
