version: "3.2"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    restart: unless-stopped
    network_mode: local_work
    ports:
      - 3000:80
    volumes:
      - /media/pi/gem:/srv
      - ./.filebrowser.json:/.filebrowser.json
      - ./data/database.db:/database.db
