version: "3.2"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: filebrowser
    network_mode: local_work
    # expose: 
    #   - 80
    ports:
      - 3000:80
    expose: 
      - 3000
    volumes:
      - /media/pi/gem:/srv
      - ./.filebrowser.json:/.filebrowser.json
      - ./data/database.db:/database.db
