version: "3.6"

networks:
  nginx:
    external: true

services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    restart: unless-stopped
    networks:
      - nginx
    ports:
      - 3000:80
    volumes:
      - /media/pi/gem:/srv
      - ./.filebrowser.json:/.filebrowser.json
      - ./data:/database
