version: "2"

user: pi:pi

services:
  drone:
    container_name: drone
    image: drone/drone
    environment:
      DRONE_GITEA_SERVER: http://git.local.cc:3000
      DRONE_GITEA_CLIENT_ID: 9b47eff7-f2f2-48ba-9af2-d903033898c1
      DRONE_GITEA_CLIENT_SECRET: Y9GUeRBtmjKSQv4Zg1cXogfpG8_Np6pX1N6Z8BYlFTM=
      DRONE_RPC_SECRET: 8030801b6299170647a1803df825430a
      DRONE_SERVER_HOST: drone.local.cc:3500
      DRONE_SERVER_PROTO: http
    volumes:
      - ./data-drone:/data
    ports:
      - 3500:80
  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone.local.cc:3500
      DRONE_RPC_SECRET: 8030801b6299170647a1803df825430a
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone-runner.local
    ports:
      - 3501:3000
