version: "3"

services:
  nginx:
    restart: unless-stopped
    image: nginx:1
    network_mode: local_work
    volumes:
      # `ro` means read only
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80