version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1
    network_mode: local_work
    restart: unless-stopped
    volumes:
      # `ro` means read only
      - ./conf:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80