version: "3.6"

networks:
  nginx:
    name: nginx

services:
  nginx:
    image: nginx:1
    networks:
      - nginx
    volumes:
      # `ro` means read only
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80