version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    network_mode: local_work
    volumes:
      # `ro` means read only
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80