version: "3"

services:
  verdaccio:
    build: .
    container_name: verdaccio
    network_mode: local_work
    environment: 
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=http
    ports:
      - 4873:4873
    volumes:
      - "./data-storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
    restart: unless-stopped

volumes:
  verdaccio:
    driver: local