version: '3'
services:
  netdata:
    network_mode: local_work
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    # set to fqdn of host
    hostname: monitor.local.cc 
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro