version: "3"

networks:
  nginx:
    external: true

services:
  xray:
    container_name: xray
    image: teddysun/xray:1.5.2
    networks:
      - nginx
    ports:
      - 7777
      - 7778
    volumes:
      - ./enabled-conf:/etc/xray
      - ./log:/var/log/xray
    command:
      - xray
      - run
      - -confdir
      - /etc/xray
