version: "3"

services:
  xray:
    container_name: xray
    image: teddysun/xray:1.5.2
    ports:
      - 7777:7777
      - 7778:7778
    volumes:
      - ./enabled-conf:/etc/xray
      - ./log:/var/log/xray
    command:
      - xray
      - run
      - -confdir
      - /etc/xray
